# Generated by Django 2.1.7 on 2019-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
